src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
#[ORM\Entity(repositoryClass: ServiceRepository::class)]
class Service
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    #[Assert\NotBlank(message:"champ obligatoire")]
    private ?string $nom_service = null;

    #[ORM\Column(length: 20)]
    #[Assert\NotBlank(message:"champ obligatoire")]
    private ?string $type_service = null;

    #[ORM\OneToMany(mappedBy: 'service_affecter', targetEntity: Chambre::class)]
    private Collection $chambres;

    #[ORM\OneToMany(mappedBy: 'service', targetEntity: Reservation::class)]
    private Collection $reservations;

    public function __construct()
    {
        $this->chambres = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomService(): ?string
    {
        return $this->nom_service;
    }

    public function setNomService(string $nom_service): self
    {
        $this->nom_service = $nom_service;

        return $this;
    }

    public function getTypeService(): ?string
    {
        return $this->type_service;
    }

    public function setTypeService(string $type_service): self
    {
        $this->type_service = $type_service;

        return $this;
    }

    /**
     * @return Collection<int, Chambre>
     */
    public function getChambres(): Collection
    {
        return $this->chambres;
    }

    public function addChambre(Chambre $chambre): self
    {
        if (!$this->chambres->contains($chambre)) {
            $this->chambres->add($chambre);
            $chambre->setServiceAffecter($this);
        }

        return $this;
    }

    public function removeChambre(Chambre $chambre): self
    {
        if ($this->chambres->removeElement($chambre)) {
            // set the owning side to null (unless already changed)
            if ($chambre->getServiceAffecter() === $this) {
                $chambre->setServiceAffecter(null);
            }
        }

        return $this;
    }
    public function __toString(){
        

        return (string) $this-> getNomService();
       


    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setService($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getService() === $this) {
                $reservation->setService(null);
            }
        }

        return $this;
    }
}

src/Form/ServiceType.php
<?php

namespace App\Form;

use App\Entity\Service;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ServiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_service')
            ->add('type_service')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Service::class,
        ]);
    }
}

src/Controller/ServiceController.php
<?php

namespace App\Controller;

use App\Entity\Service;
use App\Form\ServiceType;
use App\Repository\ServiceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Dompdf\Dompdf;
use Dompdf\Options;

#[Route('/service')]
class ServiceController extends AbstractController
{
    #[Route('/back', name: 'app_service_index1', methods: ['GET'])]
    public function index(ServiceRepository $serviceRepository, PaginatorInterface $paginator 
    , Request $request): Response
    {
        $service = $serviceRepository->findAll();
        $service = $paginator->paginate(
            $service, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            4);  /*limit per page*/
        return $this->render('service/index.html.twig', [
            'services' => $service,
    
        ]);
    } 

    #[Route('/front', name: 'app_service_index', methods: ['GET'])]
    public function indexFront(ServiceRepository $serviceRepository): Response
    {
        return $this->render('service/indexFront.html.twig', [
            'services' => $serviceRepository->findAll(),
            
        ]);
    }

    #[Route('/new', name: 'app_service_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ServiceRepository $serviceRepository): Response
    {
        $service = new Service();
        $form = $this->createForm(ServiceType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $serviceRepository->save($service, true);

            return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('service/new.html.twig', [
            'service' => $service,
            'form' => $form,
        ]);
    }

    #[Route('/pdf/{id}', name: 'service_pdf', methods: ['GET'])]
    public function pdf(Service $service ,ServiceRepository $serviceRepository): Response
    {   $service = new Service();
    
        $pdfOptions = new Options();
       
        $pdfOptions->set('defaultFont', 'Arial');
        
        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);
        
        
        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('service/pdffile.html.twig', [
            'services' => $serviceRepository->findAll(),
            'service' => $service,
        ]);
        
        // Load HTML to Dompdf
        $dompdf->loadHtml($html);
        
        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A6', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("service.pdf", [
            "Attachment" => false
        ]);
    }

    #[Route('/{id}', name: 'app_service_show', methods: ['GET'])]
    public function show(Service $service): Response
    {
        return $this->render('service/show.html.twig', [
            'service' => $service,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_service_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Service $service, ServiceRepository $serviceRepository): Response
    {
        $form = $this->createForm(ServiceType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $serviceRepository->save($service, true);

            return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('service/edit.html.twig', [
            'service' => $service,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_service_delete', methods: ['POST'])]
    public function delete(Request $request, Service $service, ServiceRepository $serviceRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$service->getId(), $request->request->get('_token'))) {
            $serviceRepository->remove($service, true);
        }

        return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/service/_delete_form.html.twig
<form method="post" action="{{ path('app_service_delete', {'id': service.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ service.id) }}">
    <button class="btn">Delete</button>
</form>

templates/service/_form.html.twig
{{ form_start(form , {'attr':{'novalidate':'novalidate'}}) }}
 <div class="form-group">
      {{ form_label(form.nom_service) }}
      {{ form_widget(form.nom_service) }} 
      {{ form_errors(form.nom_service) }}
</div>
 <div class="form-group">
      {{ form_label(form.type_service) }}
      {{ form_widget(form.type_service) }} 
      {{ form_errors(form.type_service) }}
</div>
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/service/edit.html.twig
{% extends 'dashboard.html.twig' %} 

{% block title %}Edit Service{% endblock %}

{% block body %}
    <h1>Edit Service</h1>

    {{ include('service/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_service_index') }}">back to list</a>

    {{ include('service/_delete_form.html.twig') }}
{% endblock %}

templates/service/index.html.twig
{% extends 'dashboard.html.twig' %} 

{% block title %}Service index{% endblock %}

{% block contenu %}
    <h1>Service index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_service</th>
                <th>Type_service</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for service in services %}
            <tr>
                <td>{{ service.id }}</td>
                <td>{{ service.nomService }}</td>
                <td>{{ service.typeService }}</td>
                <td>
                    <a href="{{ path('app_service_show', {'id': service.id}) }}">show</a>
                    <a href="{{ path('app_service_edit', {'id': service.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_service_new') }}">Create new</a>
    <a href="{{ path('service_pdf', {'id': 2 }) }}">pdf</a>

<div class="container py-5">
		<div class="d-flex justify-content-center">
  {{ knp_pagination_render(services) }}

</div>
	</div>        
{% endblock %}
 

templates/service/indexFront.html.twig
{% extends 'base.html.twig' %} 



{% block Service %}
    

 
    
      
        {% for service in services %}
           
             
                <h1>{{ service.nomService }}</h1> </br>
                

         
          
        {% else %}
            
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
   

{% endblock %}

templates/service/new.html.twig
{% extends 'dashboard.html.twig' %} 

{% block title %}New Service{% endblock %}

{% block contenu %}
    <h1>Create new Service</h1>

    {{ include('service/_form.html.twig') }}

    <a href="{{ path('app_service_index') }}">back to list</a>
{% endblock %}

templates/service/pdffile.html.twig
{% block body %}
<div>
<div >-------------------------------------------------------</div>
<div class="center" style=" font-style: normal; color: rgb(75, 100, 86); ">les services</div>
 {% for ser in services %}
<h1 style="font-weight: 700; font-style: italic; color: rgb(75, 100, 86); "> service{{ser.id}} :{{ ser.nomService }}</h1> 
 {% endfor %}
<div >-----------------------------</div>




<div >-------------------------------------------------------</div>
</div>

    
{% endblock %}

templates/service/show.html.twig
{% extends 'dashboard.html.twig' %} 

{% block title %}Service{% endblock %}

{% block contenu %}
    <h1>Service</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ service.id }}</td>
            </tr>
            <tr>
                <th>Nom_service</th>
                <td>{{ service.nomService }}</td>
            </tr>
            <tr>
                <th>Type_service</th>
                <td>{{ service.typeService }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_service_index') }}">back to list</a>

    <a href="{{ path('app_service_edit', {'id': service.id}) }}">edit</a>
    <a href="{{ path('service_pdf', {'id': service.id }) }}">pdf</a>

    {{ include('service/_delete_form.html.twig') }}
{% endblock %}